export enum SyntaxKind {
  EOF,
  // Everything outside the <?php tags
  RawToken,
  PhpOpenToken,

  // Literals
  AmpersandAmpersandToken,
  AmpersandToken,
  ExclamationEqualToken,
  ExclamationToken,
  QuestionToken,
  BraceLToken,
  BraceRToken,
  ColonColonToken,
  ColonToken,
  CommaToken,
  EqualEqualToken,
  EqualToken,
  GreaterEqualToken,
  GreaterToken,
  HatToken,
  LessEqualToken,
  LessToken,
  MinusMinusToken,
  MinusToken,
  ParenLToken,
  ParenRToken,
  PipePipeToken,
  PipeToken,
  PlusPlusToken,
  PlusToken,
  SlashToken,
  StarToken,
  TildeToken,
  DotToken,
  SemiColonToken,
  VariableToken,
  AtToken,
  ArrowToken, // ->


  // Virtual
  IdentifierToken,
  WhitespaceToken,
  NumberToken,
  StringToken,

  // Keywords
  HaltCompilerKeyword,
  AbstractKeyword,
  AndKeyword,
  ArrayKeyword,
  AsKeyword,
  BreakKeyword,
  CallableKeyword,
  CaseKeyword,
  CatchKeyword,
  ClassKeyword,
  CloneKeyword,
  ConstKeyword,
  ContinueKeyword,
  DeclareKeyword,
  DefaultKeyword,
  DieKeyword,
  DoKeyword,
  EchoKeyword,
  ElseKeyword,
  ElseifKeyword,
  EmptyKeyword,
  EndDeclareKeyword,
  EndForKeyword,
  EndForEachKeyword,
  EndIfKeyword,
  EndSwitchKeyword,
  EndWhileKeyword,
  EvalKeyword,
  ExitKeyword,
  ExtendsKeyword,
  FinalKeyword,
  FinallyKeyword,
  FnKeyword,
  ForKeyword,
  ForEachKeyword,
  FunctionKeyword,
  GlobalKeyword,
  GotoKeyword,
  IfKeyword,
  ImplementsKeyword,
  IncludeKeyword,
  IncludeOnceKeyword,
  InstanceofKeyword,
  InsteadofKeyword,
  InterfaceKeyword,
  IssetKeyword,
  ListKeyword,
  MatchKeyword,
  NamespaceKeyword,
  NewKeyword,
  OrKeyword,
  PrintKeyword,
  PrivateKeyword,
  ProtectedKeyword,
  PublicKeyword,
  ReadonlyKeyword,
  RequireKeyword,
  RequireOnceKeyword,
  ReturnKeyword,
  StaticKeyword,
  SwitchKeyword,
  ThrowKeyword,
  TraitKeyword,
  TryKeyword,
  UnsetKeyword,
  UseKeyword,
  VarKeyword,
  WhileKeyword,
  XorKeyword,
  YieldKeyword,


  // Php doesnt consider these keywords but i do
  TrueKeyword,
  FalseKeyword,
  FromKeyword,
}